baseURL = "https://c3labs.io/"
languageCode = "en-us"
title = "C3 Labs - The C3 Protocol"
theme = "c3"
[params]
  description = "Create useful dApps in any software language. With C3 developers can create complex or robust products without having to learn Solidity or use confined systems like EVM or Web Assembly."
	keywords = "c3 labs, c3 protocol, blockchain, decentralized applications, dapps, evm, wasm, ethereum virtual machine, web assembly, eos, ethereum, bitcoin, neo, cardano, dfinity, languages, frameworks, agnostic, layer 2, layer 1, tutorial, protocol, sdk, go, golang, rust, c++, java, python, java, javascript, node.js, php, wordpress, lua, elixir, perl, ruby, microsoft .net, enterprise, permisionless, token, easy to use, custom blockchain, plasma, state channels, cryptocurrency, digital currency"
